### PR TITLE
DynamoDB Support

### PR DESCRIPTION
**Pull request by maartenvanderhoef**
## What

DynamoDB Support

## Why

Always available at AWS, no need to take care of a KV cluster. Would love to see Traefik to use it.

## Info

@tskinn made this PR https://github.com/docker/libkv/pull/146  to LibKV two years ago, I just added some tests and made minor changes. I am not an expert on DynamoDB nor Golang, so I could use some help.

### CODE REVIEW

**Comment by tskinn** [comment]
Nice work! Looking back though I think there are some optimizations we can make depending on how the primary/secondary key are setup in dynamodb. I will try to look a bit deeper later tonight.

**Comment by maartenvanderhoef** [comment]
@tskinn Thanks & great that you're here, 99% is your work. I'm sure you didn't expect this after 2 years :-).

**Comment by maartenvanderhoef** [comment]
Just sad that I'm blind, there was already a PR open for DDB..

**Comment by tskinn** [comment]
Haha yeah! So the way that it is written now it is kind of wasteful. DynamoDB has some subtleties that I didn't really understand when I first wrote this up. 

For example, if you run `List()` it does a scan and downloads the entire database which obviously isn't a great idea. The ideal way to get around this in dynamodb is to do a query which would allow us to do something like "get all keys that start with this path." But in order to be able to do a query the table needs to have a primary and secondary index. 

What would be a good schema for our primary and secondary index? 

For starters, we shouldn't have the same primary key for everything. IYou can only have 10 GBs of stuff per primary key (all items with same primary key are stored on same shard and shards are at most 10GB). I don't know if it is common to have more that 10GB of data with these KV stores but its possible.

So I think we need a way to create primary index from the key.
It seems like the pattern with most of the key/value stores is to lay keys out like directories with `/` as separators. So, we could split the key by `/` and take the first result and make that the primary key and the whole key as the secondary index. That way we could at least have 10GB of storage for every top level directory which seems reasonable. (but who knows?)

Anyways I don't know if this makes any sense but this is what I was thinking when I saw this PR.

**Comment by tskinn** [comment]
oh whoops haha. No worries. Looks like the other PR does similar things with scan. Changing it does paint you into a corner a little bit but whatever. Anyways hopefully the other PR gets merged then!

**Comment by maartenvanderhoef** [comment]
At least something is moving one way or the other.. Closing in favor of https://github.com/abronan/valkeyrie/pull/11

**Pull request closed without merging**
