### PR TITLE
Go modules support

### PR DESCRIPTION
**Pull request by victorcoder**
## Background

Currently without go modules the dependencies and transitive deps are downloaded from their master branch, this sometimes can cause issues or incompatibilities with the dependency stable versions.

## Implementation

Providing `go.mod` with a set of known working pinned versions, ensure testing and programs using this lib will use the correct versions of the dependencies.

Also tune `.travis.yml` to use go modules instead of the versionless `go get`

As a bonus: etcdv3 client needs to come from the old etcd url import, because the stable version in the repo has no yet renamed it's import urls to the new `go.etcd.io`

### CODE REVIEW

**Comment by abronan** [comment]
Thanks @victorcoder, I added a constraint for the commits to be signed. If you could please force push signing this commit and we could thus proceed and merge this :)

**Comment by victorcoder** [comment]
Done @abronan, thanks!

**Comment by victorcoder** [comment]
Now GPG signed

**Comment by abronan** [comment]
I actually meant just signing-off the commit, but maybe I messed up in the settings let me see :p

**Comment by victorcoder** [comment]
All signs FTW

**Pull request merged**
