### PR TITLE
Add Consul token support

### PR DESCRIPTION
**Pull request by Dudesons**
Signed-off-by: Damien Goldenberg <damdam.gold@gmail.com>

### CODE REVIEW

**Comment by abronan** [comment]
Hi @Dudesons, sorry for the very long latency, I'm in the process of adding more maintainers to this repository in order to keep it going. There seems to be an issue with the rebase (maybe a GitHub bug though showing that commit), do you mind trying to push again and we'll take a look at it. Hopefully this should pass the CI this time. Thanks!

**Comment by victorcoder** [comment]
Hi @Dudesons, are you still interested in merging this PR? It would be a great addition.

**Comment by Dudesons** [comment]
Hi @abronan @victorcoder , yes sorry I forgot, I'll try to do that before the end of the week

**Comment by victorcoder** [comment]
@Dudesons I tried to rebuild it again but it is still failing in some deps. Could you merge or rebase with master, that should fix it. Thanks

**Comment by Dudesons** [comment]
@victorcoder I rebased on master but the build fail.
I try in local but I can't reproduce the error, I don't find a way to  trigger the rebuild.

**Comment by victorcoder** [comment]
@Dudesons seems that http://apache.cs.utah.edu/zookeeper/zookeeper-3.4.12 is removed. Could you please update https://github.com/abronan/valkeyrie/blob/master/.travis.yml#L26 to 3.4.13?

**Comment by victorcoder** [comment]
Thanks @Dudesons, CI passing!

**Pull request merged**
